# Permalinks
permalink:           pretty

# Setup
title:               wildtree's blog
tagline:             anyone got an idea for a tagline?

url:                 https://thewildtree.github.io
paginate:            5
baseurl:             "https://thewildtree.github.io"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Piotrek Brzeziński
  url:               https://twitter.com/thewildtree
  email:             thewildtree@outlook.com

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

plugins:
  [jekyll-paginate]
